######################## default configuration ####################
baseURL = "sergiosole.dev"
title = "Sergio Sole - CV"
theme = "port-hugo"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Portfolio"
URL = "#portfolio"
weight = 3


#################### default parameters ################################
[params]
logo_light = "images/logo.png"
logo_dark = "images/logo.png"
copyright = "Based on Port-Hugo Theme. Copyright Sergio Sole &copy;"
# Meta data
description = "Sergio Sole's CV Homepage"
author = "Sergio sergiosole"
favicon = "images/favicon_2_64-alpha.png"


# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/FalkenStein42"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://linkedin.com/in/sergio-solé-rodríguez-606902233"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:sergio@sergiosole.dev"

contentDir = "content/english"
weight = 1
home = "Home"
